### ISSUE TITLE
Refactor navigation bar

### ISSUE THREAD

**Issue by enriquemorenotent** [peschina/Pomodoro-clock#3]
@peschina:

I dare you to refactor `<NavigationBar>` into a functional component, using hooks :)

I will be happy to review it for you.

**Comment by peschina** [comment]
There you go :)
I'm afraid this component has too many responsibilities though...

**Comment by enriquemorenotent** [comment]
Tip:

Instead of this:
```js
const Navigationbar = props => {
	const {
		prop1,
		prop2,
		prop3,
	} = props;
```

you can do this:

```js
const Navigationbar = ({ prop1, prop2, prop3 }) => {
```

**Comment by enriquemorenotent** [comment]
Also, the schema:

```js
	const schema = {
		workTime: Joi.number()
			.required()
			.min(1)
			.label("Time for work"),
		shortBreakTime: Joi.number()
			.required()
			.min(1)
			.label("Time for short break"),
		longBreakTime: Joi.number()
			.required()
			.min(1)
			.label("Time for long break"),
		lBDelay: Joi.number()
			.required()
			.label("Long break delay")
	};
```

It doesnt really have any dependency with the component, no? You could very well take it out to its own file.

```js
import schema from '...'
```

**Comment by peschina** [comment]
Thanks Enrique!
Now it looks better indeed :)

**Comment by enriquemorenotent** [comment]
Very nice. Another improvement:

Instead of

```js
<ModalSettings
  show={showSettings}
  workTime={workTime}
  shortBreakTime={shortBreakTime}
  longBreakTime={longBreakTime}
  lBDelay={lBDelay}
  theme={theme}
  sound={sound}
  onClose={handleCloseSettings}
  onChange={onChange}
/>
```

You can use

```js
<ModalSettings
	{...{ workTime, shortBreakTime, longBreakTime, lBDelay, theme, sound, onChange }}
	show={showSettings}
	onClose={handleCloseSettings}
/>

```

Basically anytime the prop and the variable have the same name

**Comment by enriquemorenotent** [comment]
But there is a better way to solve that actually... As you see, you pass a lot of props to `<NavigationBar>` just because the Modal box inside it uses it.

Would you dare to try the [Context API](https://reactjs.org/docs/context.html), to fix that? There is even a hook `useContext` that makes it extra easy.

**Comment by peschina** [comment]
This has been really interesting! I wasn't familiar with that syntax, nor with the context API :)
Thanks!!

**Comment by enriquemorenotent** [comment]
Good job!
