### ISSUE TITLE
Bug: Countdown resets on opening settings

### ISSUE THREAD

**Issue by enriquemorenotent** [peschina/Pomodoro-clock#4]
Steps to reproduce:
1. Start countdown
2. Open settings modal box
3. Close settings modal box

The timer has reset, even though we have not changed anything!

**Comment by enriquemorenotent** [comment]
@peschina Can you reproduce the error?

**Comment by peschina** [comment]
Yes, I can. I'm looking it up now, and it seems like there are quite some things that went wrong. I originally meant to reset any running session if there was a change that would affect the timer, but that is bugged, too. I will rethink the method that is triggered when the settings modal closes :)

**Comment by enriquemorenotent** [comment]
Part of the problem is that you have too much state inside "App". In react, is a good idea to lift the state, if it is used in many components, BUT do not lift it anymore than that.

As for my advice, rethink the position of the state for things like <Timer> and <TimerControls>

**Comment by peschina** [comment]
Thanks @enriquemorenotent!
I momentarily used a different approach to fix the bug. I agree that there are quite a lot of props in state, but most of them affect timer, sessions and settings at the same time, so it just seemed easier to have them on top.
I think that I'll try moving down state that regards settings, and leave on top only was is strictly necessary for timer handling, and I'll see what to do from there :)
