### ISSUE TITLE
Rising validation

### ISSUE THREAD

**Issue by enriquemorenotent** [peschina/Pomodoro-clock#6]
There is no reason why the validation could not be done on the `<ModalSettings>` component. You could just fire the event "Save Changes" if the validation passes.

Also, why some settings apply immediately, like "theme" or "sound", but other require you to close the modal Box? Seems a little inconsistent, and they make the code harder to write. I would recommend you to make them all apply once the modal is closed.

Or even better, add a "Save" button, so the user has the option to cancel when closing the modal :)

**Comment by peschina** [comment]
I plan to move that Save button in a pop-up that opens when you close the modal, or something like that.

**Comment by enriquemorenotent** [comment]
Wouldnt it be more conventional to show it in the modal box where the form is?

**Comment by peschina** [comment]
Well, I was thinking about it. That would be where it is now, right? My only doubt is that if I forget to save the changes or unintentionally just close the modal nothing happens, and I have to fill in the form again. Do you think that would be okay anyways?
Thanks! :)

**Comment by enriquemorenotent** [comment]
Well, it is pretty standard behavior, don't you think? I don't know any website that does it differently.

**Comment by peschina** [comment]
You're right :) I'll leave it as it is.

**Comment by peschina** [comment]
Thanks a lot :)
