### ISSUE TITLE
Maybe using a format validator?

### ISSUE THREAD

**Issue by enriquemorenotent** [peschina/Pomodoro-clock#7]
It is a good idea to have constant format conventions throught your whole project. That means:
* Tabs or spaces?
* Single quotes or double quotes?
* Semicolons at the end?
* and some more...

To help you with this, I recommend you take a look at [Prettier](https://prettier.io/), a plugin that will automatically format your files "on save", and it will enforce other people working on your code to follow them.

All you have to do is add a file `.prettierrc` at the base of the folder, with the proper configuration. (And of course, install the plugin in your editor)

**Comment by peschina** [comment]
Thanks for the advice! :)
I'm almost sure that I'm already using Prettier, but clearly with no configuration file. I will fix that tonight.

**Comment by peschina** [comment]
Done :)
